platform :ios, '12.0'
use_frameworks!  

source 'https://github.com/appodeal/CocoaPods.git'
source 'https://cdn.cocoapods.org/'

def appodeal
    pod 'Appodeal', '3.1.3'
    pod 'APDAdColonyAdapter', '3.1.3.0'
    pod 'BidMachineAdColonyAdapter', '~> 2.3.0.0'
    pod 'APDAdjustAdapter', '3.1.3.0'
    pod 'APDAppLovinAdapter', '3.1.3.0'
    pod 'APDAppsFlyerAdapter', '3.1.3.0'
    pod 'APDBidMachineAdapter', '3.1.3.0' # Required
    pod 'BidMachineMintegralAdapter', '~> 2.3.0.0'
    pod 'BidMachineAmazonAdapter', '~> 2.3.0.0'
    pod 'BidMachineCriteoAdapter', '~> 2.3.0.0'
    pod 'BidMachineSmaatoAdapter', '~> 2.3.0.0'
    pod 'BidMachineTapjoyAdapter', '~> 2.3.0.0'
    pod 'BidMachinePangleAdapter', '~> 2.3.0.0'
    pod 'APDFirebaseAdapter', '3.1.3.0'
    pod 'APDGoogleAdMobAdapter', '3.1.3.0'
    pod 'APDIABAdapter', '3.1.3.0' # Required
    pod 'APDIronSourceAdapter', '3.1.3.0'
    pod 'APDFacebookAdapter', '3.1.3.0'
    pod 'APDMetaAudienceNetworkAdapter', '3.1.3.0'
    pod 'BidMachineMetaAudienceAdapter', '~> 2.3.0.0'
    pod 'APDMyTargetAdapter', '3.1.3.0'
    pod 'BidMachineMyTargetAdapter', '~> 2.3.0.0'
    pod 'APDStackAnalyticsAdapter', '3.1.3.0' # Required
    pod 'APDUnityAdapter', '3.1.3.0'
    pod 'APDVungleAdapter', '3.1.3.0'
    pod 'BidMachineVungleAdapter', '~> 2.3.0.0'
    pod 'APDYandexAdapter', '3.1.3.0'
end

target 'AppodealTest' do
    project 'AppodealTest.xcodeproj'
    appodeal
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
  end
 end
end
